name: iv20241038-app

services:
  db:
    image: mysql
    container_name: iv20241038-db
    ports:
      - "3306:3306"
    env_file:
      - ./env/database.env
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_init/:/docker-entrypoint-initdb.d
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 6
    restart: always
  
  wordpress:
    image: wordpress 
    container_name: iv20241038-wp
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:80"
    env_file:
      - ./env/wp.env
    networks:
      - app-network
    volumes:
      - ./wordpress:/var/www/html/
    restart: always

networks:
  app-network:
    

volumes:
  mysql_data:
   
   